### ISSUE TITLE
Could you provide link to download a trained pca model?

### ISSUE THREAD

**Issue by uzeful** [corenel/yt8m-feature-extractor#1]
Hi, Yusu, 
Since I have only download a little part of the youtube-8m videos, thus I want to request a well trained model on the large scale dataset. Could you share a link to download your trained model?

**Comment by corenel** [comment]
Here's [download link](https://drive.google.com/file/d/0B0AsKkiz_kZRcXZYS2pzWGYzSGM/view?usp=sharing) (on Google Drive).

FYI, I also download only a part of videos of yt8m dataset (~200GB) to trian the PCA model. And the output features with trained PCA model is totally different from the original ones (tested on the same video from yt8m dataset, downloaded by its `vid` in the `tfrecord` file). I don't know it's caused by inefficient data or some unreleased encoding details by Google. I tried to consult some authors of the paper about it but finally got nothing.

So currently it's **not able** to directly use this repo to encode videos and test them by models trained on the original yt8m dataset. **You may need to re-train the model.**

**Comment by uzeful** [comment]
I noticed that you have directly used the consecutive frames without sampling in decode.py, could this factor be the problem?

**Comment by corenel** [comment]
Wow, that may be the case! I misunderstood this sentence `we decode each
video at 1 frame-per-second up to the first 360 seconds (6 minutes)` when implementing.
But I'm working on another project at present, and can not promise when to fix. Maybe you could do the work and make a pull request.

**Comment by uzeful** [comment]
Ok, because right now, I want to use your code to extract the video features for my project (due in few days later), thus later I will try to revise the code and make the pull request.

**Comment by corenel** [comment]
Google now share their own tools with pre-trained model. That'd better to use theirs.

https://github.com/google/youtube-8m/tree/master/feature_extractor
